### ISSUE TITLE
Weird Tag Mismatch

### ISSUE THREAD

**Issue by justgo97** [alliedmodders/amxmodx#561]
i get a tag mismatch with this code : 

```
#include <amxmodx>

enum {
    x,
    y,
    z
}

enum _:ORIGIN_DATA{
    Float:Origin[3],
    OriginTeam
}

public plugin_init()
{
    new TestOrigin[ORIGIN_DATA]

    TestOrigin[Origin][x] = 1.0

    server_print("TestOrigin[x] = %f", TestOrigin[Origin][x])
}
```
Log output :

```
AMX Mod X Compiler 1.8.3-dev+5181
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2013 AMX Mod X Team

g:\2018\amx\Array_Tag.sma(18 -- 20) : warning 213: tag mismatch
Header size:            172 bytes
Code size:              132 bytes
Data size:               96 bytes
Stack/heap size:      16384 bytes
Total requirements:   16784 bytes

1 Warning.
Done.
```

**Comment by Mistrick** [comment]
This is limitation of PAWN in amxx. I think nobody want to upgrade/fixing this old thing.

**Comment by justgo97** [comment]
@Arkshine Well i will go with #define as it gets the job done with less weirdness but IMO this should be fixed one day.

**Comment by Arkshine** [comment]
I see no bug, it's just how Pawn works. `enum` is just a pseudo-struct. It's for sure fairly arguable design.

**Comment by WPMGPRoSToTeMa** [comment]
Macro is dangerous here because `x` is often used as variable name.

**Comment by Arkshine** [comment]
With a macro, the plugin can't compile. With an enum, you will get just a warning. You still have some information.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine I think we can add pseudo-dot-structs from Pawn upstream to AMXX Pawn compiler.

**Comment by Arkshine** [comment]
That would be cool. I hope someone will have the time to give a try.
